"""empty message

Revision ID: 472a6e6d214c
Revises: 2bea490d741a
Create Date: 2025-02-09 00:00:40.550781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '472a6e6d214c'
down_revision = '2bea490d741a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_steps', schema=None) as batch_op:
        # Drop the foreign key constraint by specifying the constraint name
        batch_op.drop_constraint('workflow_steps_workflow_id_fkey', type_='foreignkey')  # Replace with actual constraint name
        batch_op.drop_column('workflow_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_steps', schema=None) as batch_op:
        # Add the workflow_id column back
        batch_op.add_column(sa.Column('workflow_id', sa.INTEGER(), nullable=False))

        # Recreate the foreign key constraint with the correct name (use your original constraint name here)
        batch_op.create_foreign_key('workflow_steps_workflow_id_fkey', 'workflows', ['workflow_id'], ['id'])  # Define the correct constraint name

    # ### end Alembic commands ###

