"""Model changes- due date column added on task

Revision ID: 122202f44fce
Revises: dd6849941622
Create Date: 2024-11-02 15:49:48.825955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122202f44fce'
down_revision = 'dd6849941622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
