"""add taxes table
:


Revision ID: 350d482ce220
Revises: 
Create Date: 2024-11-11 19:49:45.724358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350d482ce220'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_invoice_taxes',
    sa.Column('tax_type', sa.String(length=50), nullable=False),
    sa.Column('tax_subtype', sa.String(length=50), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_invoice_taxes')
    # ### end Alembic commands ###
