"""Add workflow_id to case model

Revision ID: 9b9c64b0cf23
Revises: df8c34b8ae41
Create Date: 2024-10-29 05:27:14.401624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b9c64b0cf23'
down_revision = 'df8c34b8ae41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflow_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_case_workflow', 'workflows', ['workflow_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_constraint('fk_case_workflow', type_='foreignkey')
        batch_op.drop_column('workflow_id')

    # ### end Alembic commands ###
