"""Additions to models

Revision ID: b636aaec8282
Revises: 9b9c64b0cf23
Create Date: 2024-10-29 20:12:36.842562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b636aaec8282'
down_revision = '9b9c64b0cf23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflow_id', sa.Integer(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.create_foreign_key('fk_case_status_workflow', 'workflows', ['workflow_id'], ['id'])

    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('case_status', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('workflow_id')

    # ### end Alembic commands ###
